# Generated by Django 4.1.2 on 2022-10-12 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbrands',
            options={'verbose_name': 'Car brand', 'verbose_name_plural': 'Car brands'},
        ),
        migrations.AlterModelOptions(
            name='carmodels',
            options={'verbose_name': 'Car model', 'verbose_name_plural': 'Car models'},
        ),
        migrations.AlterModelOptions(
            name='colors',
            options={'verbose_name': 'Color', 'verbose_name_plural': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='carmodels',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_models', to='cars.carbrands', verbose_name='Car brand'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cars.carmodels', verbose_name='Car model'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cars.colors', verbose_name='Car color'),
        ),
    ]
